# Generated by Django 6.0.6 on 2026-07-30 11:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_usd_to_ngn_rate'),
        ('projects', '0003_project_lead'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(max_length=40, unique=True)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=8)),
                ('amount_subunit', models.PositiveBigIntegerField(default=0)),
                ('usd_to_ngn_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='USD → NGN rate used')),
                ('bank_name', models.CharField(max_length=120)),
                ('bank_account_number', models.CharField(max_length=34)),
                ('bank_account_name', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('paid', 'Paid'), ('rejected', 'Rejected')], default='requested', max_length=12)),
                ('note', models.TextField(blank=True, help_text='Transfer reference, or why it was rejected.')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_withdrawals', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='withdrawals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Earning',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('developer', 'Developer share'), ('delivery_lead', 'Delivery lead share')], max_length=20)),
                ('share_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='earnings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(fields=('project', 'user', 'kind'), name='unique_earning_per_role')],
            },
        ),
    ]
