# Generated by Django 6.0.6 on 2026-07-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_withdrawal_earning'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='bank_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='failure_reason',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='recipient_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='transfer_code',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='transfer_raw',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='withdrawal',
            name='transfer_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='withdrawal',
            name='status',
            field=models.CharField(choices=[('requested', 'Requested'), ('processing', 'Sending'), ('paid', 'Paid'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='requested', max_length=12),
        ),
    ]
