# Generated by Django 6.0.6 on 2026-08-02 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_earning_kind_developer_to_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='earning',
            name='kind',
            field=models.CharField(choices=[('expert', 'Expert share'), ('delivery_lead', 'Delivery lead share'), ('business_dev', 'Business developer commission')], max_length=20),
        ),
    ]
