# Generated by Django 6.0.6 on 2026-08-16 18:26

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0007_task_earnings'),
        ('projects', '0023_project_cancellation_reason_project_cancelled_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Refund',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('requested', 'Awaiting approval'), ('approved', 'Approved'), ('processed', 'Refunded'), ('rejected', 'Rejected'), ('failed', 'Failed')], default='requested', max_length=12)),
                ('funded_from_held_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('funded_from_reserve_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('absorbed_usd', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('gateway', models.CharField(blank=True, max_length=20)),
                ('gateway_reference', models.CharField(blank=True, max_length=120)),
                ('gateway_raw', models.JSONField(blank=True, default=dict)),
                ('failure_reason', models.CharField(blank=True, max_length=255)),
                ('settled_manually', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_approved', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refunds', to='projects.project')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refunds_requested', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='ReserveEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('contribution', 'Set aside'), ('draw', 'Drawn for a refund')], max_length=12)),
                ('amount_usd', models.DecimalField(decimal_places=2, max_digits=12)),
                ('note', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='reserve_entries', to='projects.project')),
                ('refund', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reserve_entries', to='payments.refund')),
            ],
            options={
                'verbose_name_plural': 'reserve entries',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('kind', 'contribution')), fields=('project',), name='unique_reserve_contribution_per_project')],
            },
        ),
    ]
