# Generated by Django 6.0.6 on 2026-08-16 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0008_refund_reserveentry'),
        ('projects', '0024_changeorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='change_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments', to='projects.changeorder'),
        ),
    ]
