# Generated by Django 6.0.6 on 2026-08-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0009_payment_change_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='gateway',
            field=models.CharField(default='paystack', max_length=20),
        ),
    ]
