# Generated by Django 6.0.6 on 2026-07-05 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='kind',
            field=models.CharField(choices=[('system', 'System'), ('update', 'Update'), ('progress', 'Progress'), ('milestone', 'Milestone'), ('blocker', 'Blocker'), ('question', 'Question')], default='update', max_length=12),
        ),
    ]
