# Generated by Django 6.0.6 on 2026-07-30 13:30

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_backfill_project_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='delivery_lead_share_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text="Leave blank to use the site default. The platform keeps whatever the developer and lead shares don't claim.", max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Delivery lead share (%)'),
        ),
        migrations.AddField(
            model_name='project',
            name='developer_share_percent',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Leave blank to use the site default. Set a value to pay this project differently — useful for a large or unusual build.', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Developer share (%)'),
        ),
    ]
