# Generated by Django 6.0.6 on 2026-08-02 11:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_product_lines'),
        ('projects', '0007_expert_share_labels'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='product_line',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='catalog.productline'),
        ),
        migrations.AddField(
            model_name='project',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='catalog.service'),
        ),
    ]
