# Generated by Django 6.0.6 on 2026-08-02 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_business_developer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=1000)),
                ('label', models.CharField(blank=True, max_length=200)),
                ('kind', models.CharField(choices=[('figma', 'Figma'), ('drive', 'Google Drive'), ('dropbox', 'Dropbox'), ('github', 'GitHub'), ('notion', 'Notion'), ('loom', 'Loom'), ('link', 'Link')], default='link', max_length=12)),
                ('purpose', models.CharField(choices=[('reference', 'Reference'), ('deliverable', 'Deliverable')], default='deliverable', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.activity')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.project')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
