# Generated by Django 6.0.6 on 2026-08-02 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_backfill_completed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='target_date_new',
            field=models.DateField(blank=True, help_text="When delivery is promised. Leave blank until it's agreed.", null=True, verbose_name='Target date'),
        ),
    ]
