# Generated by Django 6.0.6 on 2026-08-06 06:42

import accounts.uploads
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_swap_target_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='file',
            field=models.FileField(blank=True, help_text='Streamed through an authenticated view — never a public URL.', null=True, upload_to=accounts.uploads.project_document_path, validators=[accounts.uploads.validate_project_document]),
        ),
        migrations.AddField(
            model_name='attachment',
            name='original_filename',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='attachment',
            name='size_bytes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='kind',
            field=models.CharField(choices=[('figma', 'Figma'), ('drive', 'Google Drive'), ('dropbox', 'Dropbox'), ('github', 'GitHub'), ('notion', 'Notion'), ('loom', 'Loom'), ('link', 'Link'), ('file', 'Uploaded file')], default='link', max_length=12),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='url',
            field=models.URLField(blank=True, max_length=1000),
        ),
    ]
