# Generated by Django 6.0.6 on 2026-08-16 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0020_drop_task_done'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='revision_rounds',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='activity',
            name='kind',
            field=models.CharField(choices=[('system', 'System'), ('update', 'Update'), ('progress', 'Progress'), ('milestone', 'Milestone'), ('blocker', 'Blocker'), ('question', 'Question'), ('revision', 'Changes requested')], default='update', max_length=12),
        ),
        migrations.CreateModel(
            name='RevisionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_requests', to='projects.project')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='revision_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
    ]
