# Generated by Django 6.0.6 on 2026-08-16 18:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0022_project_completed_by_project_countersigned_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='project',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects_cancelled', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='stage',
            field=models.CharField(choices=[('Submitted', 'Submitted'), ('Quoted', 'Quoted'), ('Paid', 'Paid'), ('In Progress', 'In Progress'), ('Review', 'Review'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Submitted', max_length=20),
        ),
    ]
