# Generated by Django 6.0.6 on 2026-08-16 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_organisation_organisationmember'),
        ('projects', '0026_activity_attachment_activity_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='organisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='accounts.organisation'),
        ),
    ]
