# Generated by Django 6.0.6 on 2026-08-17 00:42

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_organisation_preferred_currency'),
        ('catalog', '0002_seed_product_lines'),
        ('projects', '0028_backfill_organisations'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CycleRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ran_at', models.DateTimeField(auto_now_add=True)),
                ('dry_run', models.BooleanField(default=False)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('detail', models.TextField(blank=True)),
                ('triggered_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-ran_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='period_end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='period_start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='Engagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('monthly_amount_usd', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('1'))])),
                ('billing_day', models.PositiveSmallIntegerField(default=1, help_text='Day of the month each period starts. 1–28.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(28)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('ended', 'Ended')], default='active', max_length=10)),
                ('started_on', models.DateField()),
                ('ends_on', models.DateField(blank=True, help_text='Leave blank to run until somebody ends it.', null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('end_reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='client_engagements', to=settings.AUTH_USER_MODEL)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_engagements', to=settings.AUTH_USER_MODEL)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='accounts.organisation')),
                ('product_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engagements', to='catalog.productline')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='engagements', to='catalog.service')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='project',
            name='engagement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cycles', to='projects.engagement'),
        ),
    ]
