# Generated by Django 6.0.6 on 2026-08-24 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0029_cyclerun_project_period_end_project_period_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectfeedback',
            name='may_publish',
            field=models.BooleanField(default=False),
        ),
    ]
