# Generated by Django 6.0.6 on 2026-07-29 19:21

import django.core.validators
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def seed_rate_from_env(apps, schema_editor):
    """Carry the existing USD_TO_NGN_RATE .env value into the editable row."""
    SiteSettings = apps.get_model('accounts', 'SiteSettings')
    SiteSettings.objects.update(usd_to_ngn_rate=Decimal(str(settings.USD_TO_NGN_RATE)))


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='usd_to_ngn_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('1600.00'), help_text="Naira per 1 USD. Applied to every invoice charged in NGN from the moment it's saved — update it when the market rate moves.", max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='USD → NGN rate'),
        ),
        migrations.RunPython(seed_rate_from_env, migrations.RunPython.noop),
    ]
