# Generated by Django 6.0.6 on 2026-07-30 11:38

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_sitesettings_usd_to_ngn_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='delivery_lead_share_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('15.00'), help_text='What the delivery lead who quoted the project earns on approval. The remainder of the quote stays with the platform.', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Delivery lead share of a quote (%)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='developer_share_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), help_text="What the assigned developer earns from a project's quote once the client approves delivery. Applies to projects completed from now on.", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Developer share of a quote (%)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='min_withdrawal_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='The smallest balance a developer or delivery lead can withdraw.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Minimum withdrawal (USD)'),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=34),
        ),
        migrations.AddField(
            model_name='user',
            name='bank_name',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
