# Generated by Django 6.0.6 on 2026-07-30 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_sitesettings_delivery_lead_share_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bank_code',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='paystack_recipient_code',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
