# Generated by Django 6.0.6 on 2026-08-02 10:23

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_developer_role_to_expert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='expert_share_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), help_text="What the assigned project delivery expert earns from a project's quote once the client approves delivery. Applies to projects completed from now on.", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Expert share of a quote (%)'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='min_withdrawal_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('50.00'), help_text='The smallest balance an expert or delivery lead can withdraw.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Minimum withdrawal (USD)'),
        ),
    ]
