# Generated by Django 6.0.6 on 2026-08-02 11:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_expert_share_labels'),
        ('catalog', '0002_seed_product_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='The delivery lead this expert works under.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='team_members', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='product_lines',
            field=models.ManyToManyField(blank=True, help_text='For a delivery lead, the lines they run. For an expert, the lines they can be assigned work in.', related_name='members', to='catalog.productline'),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
