# Generated by Django 6.0.6 on 2026-08-02 13:29

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_product_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='business_dev_share_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text="Commission for the business developer who sourced a project, paid on completion. Charged only on projects that have one — a direct project keeps this in the platform's share.", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Business developer commission (%)'),
        ),
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, db_index=True, default='', help_text='Shareable code — a client signing up at /register?ref=CODE is attributed to this business developer.', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='referred_by',
            field=models.ForeignKey(blank=True, help_text='The business developer who referred this client.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referred_clients', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('client', 'Client'), ('delivery_lead', 'Delivery Lead'), ('expert', 'Project Delivery Expert'), ('business_dev', 'Business Developer')], default='client', max_length=20),
        ),
    ]
