# Generated by Django 6.0.6 on 2026-08-02 13:53

import accounts.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_business_developer'),
        ('catalog', '0002_seed_product_lines'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='applied_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='approval_status',
            field=models.CharField(choices=[('n/a', 'Not required'), ('pending', 'Pending review'), ('approved', 'Approved'), ('rejected', 'Not approved')], default='n/a', help_text="Delivery leads and business developers are reviewed before they can quote work or be paid. Clients and invited experts don't need approval.", max_length=10),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_partners', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='onboarding_step',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Shown to the applicant, so write it for them to read.'),
        ),
        migrations.CreateModel(
            name='PartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(blank=True)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('timezone_name', models.CharField(blank=True, max_length=64, verbose_name='Timezone')),
                ('years_experience', models.PositiveIntegerField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('portfolio_url', models.URLField(blank=True)),
                ('team_size_target', models.PositiveIntegerField(blank=True, null=True)),
                ('past_delivery', models.TextField(blank=True, help_text="What they've delivered before — the heart of the review.")),
                ('references_note', models.TextField(blank=True, verbose_name='References')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='partner_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('full_name', models.CharField(blank=True, max_length=150)),
                ('specialty', models.CharField(blank=True, max_length=150)),
                ('skills', models.JSONField(blank=True, default=list)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('revoked', 'Revoked')], default='pending', max_length=10)),
                ('expires_at', models.DateTimeField(default=accounts.models._invite_expiry)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('invited_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_invitations', to=settings.AUTH_USER_MODEL)),
                ('product_lines', models.ManyToManyField(blank=True, related_name='invitations', to='catalog.productline')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('email',), name='one_pending_invitation_per_email')],
            },
        ),
    ]
