# Generated by Django 6.0.6 on 2026-08-02 22:12

import accounts.uploads
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_approve_existing_partners'),
    ]

    operations = [
        # A rename, never a drop-and-recreate: the table holds submitted
        # applications, and recreating it would delete every one of them.
        migrations.RenameModel(old_name='PartnerProfile', new_name='ProfessionalProfile'),
        migrations.AlterField(
            model_name='professionalprofile',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='professional_profile',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='cv',
            field=models.FileField(blank=True, help_text='PDF or Word document, up to 5MB. Visible to their delivery lead.', null=True, upload_to=accounts.uploads.cv_path, validators=[accounts.uploads.validate_cv], verbose_name='CV / résumé'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='cv_uploaded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text='Languages they work in, e.g. ["English", "French"].'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='certifications',
            field=models.TextField(blank=True, help_text='Qualifications and certifications, one per line.'),
        ),
        migrations.AddField(
            model_name='professionalprofile',
            name='availability_hours',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(168)], verbose_name='Availability (hours/week)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='require_kyc_for_payout',
            field=models.BooleanField(default=False, help_text='When on, an expert, delivery lead or business developer must be KYC-verified before they can withdraw. Left OFF by default so turning KYC on never silently strands people who are already owed money — switch it on once your team is verified.', verbose_name='Require identity verification before payout'),
        ),
        migrations.CreateModel(
            name='KycProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legal_name', models.CharField(blank=True, max_length=150)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=32)),
                ('address_line1', models.CharField(blank=True, max_length=200, verbose_name='Address')),
                ('address_line2', models.CharField(blank=True, max_length=200, verbose_name='Address line 2')),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100, verbose_name='State / region')),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=80)),
                ('id_type', models.CharField(blank=True, choices=[('passport', 'Passport'), ('national_id', 'National ID card'), ('drivers_licence', "Driver's licence"), ('voters_card', "Voter's card")], max_length=20)),
                ('id_number', models.CharField(blank=True, help_text='Sensitive. Returned masked by the API to everyone except the person themselves; never included in list endpoints.', max_length=60)),
                ('id_document', models.FileField(blank=True, null=True, upload_to=accounts.uploads.id_document_path, validators=[accounts.uploads.validate_id_document], verbose_name='ID document')),
                ('tax_id', models.CharField(blank=True, max_length=60, verbose_name='Tax ID / TIN')),
                ('status', models.CharField(choices=[('unsubmitted', 'Not submitted'), ('pending', 'Awaiting review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='unsubmitted', max_length=12)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, help_text='Shown to the person, so write it for them to read.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_kyc', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kyc', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'KYC record',
                'verbose_name_plural': 'KYC records',
            },
        ),
    ]
