# Generated by Django 6.0.6 on 2026-08-15 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_close_onboarding_for_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImpersonationEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(blank=True, help_text='What the admin said they were doing.', max_length=200)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('impersonator', models.ForeignKey(help_text='The admin who started the session.', on_delete=django.db.models.deletion.CASCADE, related_name='impersonations_started', to=settings.AUTH_USER_MODEL)),
                ('target', models.ForeignKey(help_text='The account they signed in as.', on_delete=django.db.models.deletion.CASCADE, related_name='impersonations_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
    ]
