# Generated by Django 6.0.6 on 2026-08-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_impersonationevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='client_silence_days',
            field=models.PositiveIntegerField(default=7, help_text="How long after reminding a client that a delivery lead may complete a project on their behalf and release the team's earnings. The clock starts at the first reminder and resets if the client says anything. A second delivery lead can countersign instead of waiting.", verbose_name="Days before a lead may close a silent client's project"),
        ),
    ]
