# Generated by Django 6.0.6 on 2026-08-16 18:26

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_sitesettings_client_silence_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='refund_admin_threshold_usd',
            field=models.DecimalField(decimal_places=2, default=Decimal('500.00'), help_text='A delivery lead can issue refunds up to this amount on their own projects. Anything larger waits for an administrator.', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Refund needing admin approval (USD)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='reserve_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text="Set aside from the platform's own share of each completed project, to fund refunds on work that has already been paid out. This never changes what an expert, delivery lead or business developer earns — it comes out of the remainder.", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name="Refund reserve (% of the platform's share)"),
        ),
    ]
