# Generated by Django 6.0.6 on 2026-08-16 21:34

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_expert_share_to_seventy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='expert_share_percent',
            field=models.DecimalField(decimal_places=2, default=Decimal('70.00'), help_text="What the assigned project delivery expert earns from a project's quote once the client approves delivery. Applies to projects completed from now on.", max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Expert share of a quote (%)'),
        ),
    ]
