# Generated by Django 6.0.6 on 2026-08-17 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_organisation_organisationmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='preferred_currency',
            field=models.CharField(blank=True, help_text="e.g. USD, GBP, EUR, NGN. Blank uses the platform default. Quotes are always agreed in USD; this is only what the client's card is charged in.", max_length=3),
        ),
    ]
