# Generated by Django 6.0.6 on 2026-08-25 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_termsacceptance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_in_leaderboard',
            field=models.BooleanField(default=True, help_text='Delivery leads and experts with enough delivered work appear on the public leaderboard. Untick to be left off it.', verbose_name='Show on the public leaderboard'),
        ),
    ]
