# Generated by Django 6.0.6 on 2026-08-02 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('tagline', models.CharField(blank=True, help_text='One line shown on the product-line card when a client is choosing.', max_length=140)),
                ('description', models.TextField(blank=True)),
                ('accent', models.CharField(default='#0FA37F', help_text="Hex colour for this line's chip and card, e.g. #7C3AED.", max_length=7)),
                ('icon', models.CharField(blank=True, help_text="Icon key from the frontend's icon set (e.g. 'grid', 'check').", max_length=40)),
                ('is_active', models.BooleanField(default=True, help_text="Inactive lines are hidden from clients and can't take new briefs. Turn a line off rather than deleting it — existing projects keep pointing at it.")),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('typical_timeline', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('product_line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='catalog.productline')),
            ],
            options={
                'ordering': ['order', 'name'],
                'constraints': [models.UniqueConstraint(fields=('product_line', 'name'), name='unique_service_per_line')],
            },
        ),
    ]
